spring:
    application:
        name: dict-miner
    config:
        import:
            - configserver:${config.server.url}
            - vault://
    cloud:
        config:
            profile: ${spring.profiles.active}
            label: main
            username: ${CONFIG_SERVER_USER}
            password: ${CONFIG_SERVER_PASS}
        vault:
            uri: https://lyolek.synology.me:8200/
            scheme: https
            authentication: approle
            app-role:
                role-id: ${DICT_MINER_VAULT_ROLE_ID}
                secret-id: ${DICT_MINER_VAULT_SECRET_ID}
            kv:
                enabled: true
                backend: secret
                default-context: ${spring.application.name}